imports:
    - "behat.yml"

default:
    extensions:
        Alex\MailCatcher\Behat\MailCatcherExtension\Extension:
            url: http://localhost:1080
            purge_before_scenario: true
        Troopers\BehatContexts\Extension:
            alias_entity:
                enabled: true
            mails:
                path: "src/Troopers/BehatContexts/Tests/Features/Fixtures"
                key: "acme_emails"
                translation:
                    firstCharacter: "f"
                    lastCharacter: "l"
